"""edit table

Revision ID: 0c532f55a715
Revises: 
Create Date: 2023-05-26 03:23:27.023187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c532f55a715'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_log', schema=None) as batch_op:
        batch_op.drop_index('id')

    op.drop_table('maintenance_log')
    with op.batch_alter_table('maintenanceReport_notification', schema=None) as batch_op:
        batch_op.drop_constraint('maintenanceReport_notification_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('maintenanceReport_notification_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('machine_id')

    with op.batch_alter_table('maintenance_schedule', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'done'),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_constraint('maintenance_schedule_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('maintenance_schedule_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('machine_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('user_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.create_foreign_key('maintenance_schedule_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('maintenance_schedule_ibfk_2', 'machine', ['machine_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.String(length=150),
               type_=mysql.ENUM('pending', 'done'),
               existing_nullable=False)

    with op.batch_alter_table('maintenanceReport_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('user_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.create_foreign_key('maintenanceReport_notification_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('maintenanceReport_notification_ibfk_2', 'machine', ['machine_id'], ['id'])

    op.create_table('maintenance_log',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('log_entry', mysql.TEXT(), nullable=False),
    sa.Column('log_date', mysql.DATETIME(), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('machine_maintenance_report_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('machine_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_updated', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], name='maintenance_log_ibfk_3'),
    sa.ForeignKeyConstraint(['machine_maintenance_report_id'], ['machine_maintenance_report.id'], name='maintenance_log_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='maintenance_log_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('maintenance_log', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=False)

    # ### end Alembic commands ###
