"""edit table

Revision ID: 479f81572b53
Revises: 5e8bb21a6dd3
Create Date: 2023-05-26 09:16:16.234239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '479f81572b53'
down_revision = '5e8bb21a6dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_schedule', schema=None) as batch_op:
        batch_op.drop_constraint('maintenance_schedule_ibfk_3', type_='foreignkey')
        batch_op.drop_column('machine_maintenance_report_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_maintenance_report_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.create_foreign_key('maintenance_schedule_ibfk_3', 'machine_maintenance_report', ['machine_maintenance_report_id'], ['id'])

    # ### end Alembic commands ###
