"""edit table

Revision ID: f054190dca5c
Revises: d9eb91fe6181
Create Date: 2023-05-26 04:30:49.762380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f054190dca5c'
down_revision = 'd9eb91fe6181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenanceReport_notification', schema=None) as batch_op:
        batch_op.drop_index('id')

    op.drop_table('maintenanceReport_notification')
    with op.batch_alter_table('maintenance_schedule', schema=None) as batch_op:
        batch_op.drop_column('completed_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_date', mysql.DATETIME(), nullable=False))

    op.create_table('maintenanceReport_notification',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_updated', mysql.DATETIME(), nullable=True),
    sa.Column('machine_maintenance_report_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('notification_datetime', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('machine_id', mysql.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], name='maintenanceReport_notification_ibfk_5'),
    sa.ForeignKeyConstraint(['machine_maintenance_report_id'], ['machine_maintenance_report.id'], name='maintenanceReport_notification_ibfk_3'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='maintenanceReport_notification_ibfk_4'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('maintenanceReport_notification', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=False)

    # ### end Alembic commands ###
